version: "3"

services:
  golang-app:
    build:
      context: ./app
    container_name: golang-log-service
    ports:
      - "8080:8080"
    volumes:
      - ./app/logs:/var/log/app

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./app/logs:/var/log/app
    command: -config.file=/etc/promtail/promtail-config.yml

  grafana:
    image: grafana/grafana:9.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
